version: "3"
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo:/data/db
    ports:
      - "6000:27017"
    env_file:
      - ./.env.local

  dashboard:
    build:
      context: .
      dockerfile: Development.Dockerfile
    ports:
      - "3000:3000"
      - "4000:4000"
    volumes:
      - .:/app
    depends_on:
      - mongo

volumes:
  mongo:
